name: xks
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=21.11b1=pyhd8ed1ab_0
  - ca-certificates=2021.10.8=ha878542_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - click=8.0.3=py39hf3d152e_1
  - coverage=6.2=py39h3811e60_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - distlib=0.3.3=pyhd8ed1ab_0
  - editdistance-s=1.0.0=py39h1a9c180_2
  - entrypoints=0.3=pyhd8ed1ab_1003
  - filelock=3.4.0=pyhd8ed1ab_0
  - identify=2.3.7=pyhd8ed1ab_0
  - importlib-metadata=4.8.2=py39hf3d152e_0
  - importlib_metadata=4.8.2=hd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.6.0=py39hef51801_0
  - ipython=7.30.1=py39hf3d152e_0
  - jedi=0.18.1=py39hf3d152e_0
  - jupyter_client=7.1.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_1
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=12_linux64_openblas
  - libcblas=3.9.0=12_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=11.2.0=h1d223b6_11
  - liblapack=3.9.0=12_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libzlib=1.2.11=h36c2ea0_1013
  - llvmlite=0.37.0=py39h1bbdace_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - more-itertools=8.12.0=pyhd8ed1ab_0
  - mypy_extensions=0.4.3=py39hf3d152e_4
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - nodeenv=1.6.0=pyhd8ed1ab_0
  - numba=0.54.1=py39h56b8d98_0
  - numpy=1.20.3=py39hdbf815f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.4=py39hde0f152_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.3.1=pyhd8ed1ab_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py39hf3d152e_2
  - pre-commit=2.16.0=py39hf3d152e_0
  - prompt-toolkit=3.0.23=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py=1.11.0=pyh6c4a22f_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pytest=6.2.5=py39hf3d152e_1
  - pytest-cov=3.0.0=pyhd8ed1ab_0
  - python=3.9.7=hf930737_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=6.0=py39h3811e60_3
  - pyzmq=22.3.0=py39h37b5a0c_1
  - readline=8.1=h46c0cb4_0
  - regex=2021.11.10=py39h3811e60_0
  - scipy=1.7.3=py39hee8e79c_0
  - setuptools=59.4.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=1.2.2=pyhd8ed1ab_0
  - tornado=6.1=py39h3811e60_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.1=py39h3811e60_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - versioneer=0.21=pyhd8ed1ab_0
  - virtualenv=20.4.7=py39hf3d152e_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - xarray=0.20.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
